// all types

// Registering
export const REGISTER_START = "REGISTER_START";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

// Login
export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

// Logout
export const LOGOUT = "LOGOUT";

// GET exersize data
export const GET_EXERCISE_START = "GET_EXERCISE_START";
export const GET_EXERCISE_SUCCESS = "GET_EXERCISE_SUCCESS";
export const GET_EXERCISE_FAIL = "GET_EXERCISE_FAIL";

// POST new exersize
export const NEW_EXERCISE_START = "NEW_EXERCISE_START";
export const NEW_EXERCISE_SUCCESS = "NEW_EXERCISE_SUCCESS";
export const NEW_EXERCISE_FAIL = "NEW_EXERCISE_FAIL";

// POST new journal entry
export const NEW_JOURNAL_START = "NEW_JOURNAL_START";
export const NEW_JOURNAL_SUCCESS = "NEW_JOURNAL_SUCCESS";
export const NEW_JOURNAL_FAIL = "NEW_JOURNAL_FAIL";

// GET journals
export const JOURNAL_START = "JOURNAL_START";
export const JOURNAL_SUCCESS = "JOURNAL_SUCCESS";
export const JOURNAL_FAIL = "JOURNAL_FAIL";

// DELETE Journal
export const DELETE_JOURNAL_START = "DELETE_JOURNAL_START";
export const DELETE_JOURNAL_SUCCESS = "DELETE_JOURNAL_SUCCESS";
export const DELETE_JOURNAL_FAIL = "DELETE_JOURNAL_FAIL";

// EDIT Journal
export const EDIT_JOURNAL_START = "EDIT_JOURNAL_START";
export const EDIT_JOURNAL_SUCCESS = "EDIT_JOURNAL_SUCCESS";
export const EDIT_JOURNAL_FAIL = "EDIT_JOURNAL_FAIL";
